nom = input()
nom = input ()
apelli = input()
apelli = input ()
print ("nom:", "apelli")
edad1 = int(input())
edad2 = int(input())
diferencia = abs(edad1 - edad2)
print("La diferencia de edades es:", diferencia, "años")